# Generated by Django 6.0.4 on 2026-05-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('sales', 'Sales'), ('sales_leader', 'Sales Leader'), ('manager', 'Manager'), ('admin', 'Admin'), ('accountant', 'Accountant'), ('designer', 'Designer')], max_length=20),
        ),
    ]
